//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASKTRACKERSYSTEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK
    {
        public int TASKID { get; set; }
        public string TASKNAME { get; set; }
        public Nullable<int> ASSIGNEDTO { get; set; }
        public Nullable<System.DateTime> DUETO { get; set; }
        public int STATUS { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
