//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace TASKTRACKERSYSTEM.Models
{
    internal class ToString
    {
        public static explicit operator ToString(TaskStatus v)
        {
            throw new NotImplementedException();
        }
    }
}